### PR TITLE
add tutorial documentation on defsrc

### PR DESCRIPTION
**Pull request by focusaurus**
Not sure if others will jive with my approach, but here's a tutorial.

### CODE REVIEW

**Comment by slotThe** [comment]
On Tue, Sep 29 2020 19:20, Peter Lyons wrote:
> Not sure if others will jive with my approach, but here&#39;s a tutorial.

Changes to the tutorial should go in `keymap/tutorial.kbd` I think; it
wouldn't make sense to have two tutorials in the same repository.

**Comment by david-janssen** [comment]
Hey there, thanks for the pull request. I'd be happy to include your contribution, but I have a few questions first. I was wondering if there was a reason you didn't make clarifications to the `keymap/tutorial.kbd`? It sort of seems like you might've overlooked that file :-).

However! There is very much something to be said for a mark-downed tutorial. Whenever I sit down to write documentation for KMonad it always ends up being a lot of text, and it is hard to find a specific issue in the `tutorial.kbd`. I was thinking of starting a wiki, Github comes with built-in support for that, I think.

This is just me brainstorming, do you guys have any ideas for what would be best? In this particular case you are actually in a better position than me, since I've never had to approach KMonad from the outside, so it is hard for me to see what is clear and what is confusing.

**Comment by david-janssen** [comment]
Oh, and more thoughts:

So I do want to avoid duplicating tutorials, 1 in `kbd` and 1 in`md` would be a headache to maintain. We would consider turning `kbd` into a 'feature-demonstration', and then move most of the text into `md` and link to `kbd`? But are 2 files easier to read than 1 big document? I don't know... Need input

**Comment by focusaurus** [comment]
So my main goal here was to author some content. I'm not that particular about where it lands ultimately. I'll offer my opinion but I'm 100% fine if you prefer embedding the tutorial(s) in a `.kbd` file. In my opinion, for a project like this, I think all documentation should live in the README.md in the repo root including overview, installation, usage, etc. I'm fine if the file is very long. Here's some of my reasoning:

- It's the file often landed on after a web search. If everything's there, more folks will find everything.
- It's easy to click a link fragment and send someone a URL to a particular heading. Of course you can link to any line in any file on github but it's not as easy and not as stable as a link to a named fragment like `#troubleshooting` even as the document evolves.

And some of my reasoning why I don't prefer the "embed the docs as comments in the config file" approach

- Less conventional at this point vs a github readme.
- Less discoverable due to the above point plus SEO
- The `.kbd` file isn't even in the `docs` folder right now. It's like the docs are being hidden.
- The `.kbd` file extension is not well-known for "here be docs", nor would I expect to find tutorials in a directory named `keymap`

And while I did discover and read that `tutorial.kbd` file, for me, it's a recipe for the following:

- spend a long time reading that whole file and the evolution of advanced buttons I may or may not need
- Look at the samples and think "Before I can use or try this tool, I need to know the weird sym name for every key on my keyboard in order and if I get it wrong I might not be able to type on my computer"
- See that there's no existing file that matches my keyboard
- Try it out having exhausted my time box for futzing with this project, get an error message, and give up.

(I came very close to ending up at the end of that path)

So I wanted something that has a small feedback loop: read a little, run 1 command, get 1 result, either proceed or troubleshoot based on the result. I think markdown lends itself to guiding a user through that better than a comprehensive reference of the button syntax and capabilities.

**Comment by david-janssen** [comment]
That is an incredibly cogent and convincing set of points you make. I will let this percolate for a bit, and will definitely take all of this into consideration.

My fear is that, as the configuration language and multi-platform options grow, the README will grow dauntingly large. What, in your experience, gives you the best interface to such a document? Just a good TOC? Or is a wiki-format at some point better?

I think also when it comes to coding, my brain stops wanting to contain files longer than like... 400 lines. But I think I might simply be a bit particular in this respect. 

@thoelze1 @slotThe @MaxGyver83 @eighal: I would love to hear your perspectives on this. After basic code-quality, documentation quality and accessibility is very important to me, but I honestly don't know what's best and am looking for opinions.

**Comment by eighal** [comment]
I'm not an experienced project manager, but I have opinions about everything, so:

1. I think it's important to write documentation as you/we go, rather than after the fact, because after the fact I can never remember what I found puzzling.  You're already doing this so great!

2. I love wikis for everything provided that there's a friendly community (doesn't matter how big), which in this case there seems to be.  I have a poster of Ward Cunningham above my bed.  (Not really.  But almost.)

**Comment by MaxGyver83** [comment]
My opinion:

* I prefer formatted documentation, with a table of contents and links to every section. But for me both Markdown or a wiki are fine.
* I think it's okay to split all documentation in separate Markdown files/wiki pages as long as everything is linked.
* Nevertheless it's good having some working example files containing some basic comments for getting started quickly. If somebody wants to do more than swapping some buttons in the example, he can check the detailed documentation.

**Comment by slotThe** [comment]
In my opinion, the best solution would be some sort of literate
configuration file (as is often achieved by using org-mode).  In absence
of that I would choose a config file with comments as documentation over
markdown any day of the week.  I'm impartial on the wiki vs. config file
part.

On Wed, Sep 30 2020 07:22, Peter Lyons wrote:
> In my opinion, for a project like this, I think all documentation
> should live in the README.md in the repo root including overview,
> installation, usage, etc. I'm fine if the file is very long.

I think this only works for small README files and quite quickly falls
apart for larger and more complicated projects.  As an example, take
xmobar's README.md file (
https://github.com/jaor/xmobar/blob/master/readme.md ).  It's definitely
comprehensive, but I doubt anyone would call it easy to navigate (I
don't actually think that anything else (besides switching from markdown
to org-mode, of course!) would be better in xmobar's case, but that's
just because there are *so* many modules).

> - It's the file often landed on after a web search. If everything's
> there, more folks will find everything.

This, to me, sounds more like the README should give a short-ish
introduction into the topic instead of a deep-dive.  Give people a small
taste and watch them fall over themselves to get more :)

> - It's easy to click a link fragment and send someone a URL to a
> particular heading. Of course you can link to any line in any file on
> github but it's not as easy and not as stable as a link to a named
> fragment like `#troubleshooting` even as the document evolves.

I think this is fair, though it would point more towards a wiki than a
single README file.  Also, while you often only have a browser to read
the README (as you've most likely just discovered the project), you will
probably read the tutorial in a text editor of your choice, which would
make things like grepping for things rather easy.

> - The `.kbd` file isn't even in the `docs` folder right now. It's like
> the docs are being hidden.
> - The `.kbd` file extension is not well-known for "here be docs", nor
> would I expect to find tutorials in a directory named `keymap`

This I agree with, my first instinct when looking for the tutorial also
was to just go into the docs directory.  Though I think this would be
fixed rather easily.

> And while I did discover and read that `tutorial.kbd` file, for me,
> it's a recipe for the following:
>
> - spend a long time reading that whole file and the evolution of
> advanced buttons I may or may not need
> - Look at the samples and think "Before I can use or try this tool, I
> need to know the weird sym name for every key on my keyboard in order
> and if I get it wrong I might not be able to type on my computer"
> - See that there's no existing file that matches my keyboard
> - Try it out having exhausted my time box for futzing with this
> project, get an error message, and give up.
>
> (I came very close to ending up at the end of that path)

That is indeed rather unfortunate and I would agree that some sort of
"quick start guide" might be helpful to get people up and running
quickly.  At the end of the day though, kmonad does have a lot of
features and "hiding" those features from new adopters might be equally
frustrating to some.

**Comment by david-janssen** [comment]
Going to close this pull-request because we need to basically rethink the entire concept of how to do documentation well. This isn't just a little command-line app, it's a keyboard configuration suite with a variety of buttons and config options.

Maybe we should expand the wiki, maybe we should make a read-the-docs, but a `tutorial.kbd` file isn't going to cut it.

**Pull request closed without merging**
