### PR TITLE
Add build instructions for Windows (using scoop) 

### PR DESCRIPTION
**Pull request by MaxGyver83**
Same PR as some minutes ago but now against `kmonad/kmonad` with an updated repo in the `git clone` command.

### CODE REVIEW

**Comment by slotThe** [comment]
The ownership transfering here is remarkably smart, so your old PR is already live (14c6ea674225d0596f800b589c407803fed7d110)!

The URL still has to be changed, so I suppose you can use this PR to just do that so it's not wasted

**Comment by MaxGyver83** [comment]
OK, then I don't know why GitHub told me, I was **two** commits ahead. I assumed the first commit didn't make it into `kmonad/kmonad`, only into `david-janssen/kmonad`. When I resolve this one, is it okay to commit the merge into master? Otherwise, they suppose creating a new branch.

**Comment by MaxGyver83** [comment]
Thanks for resolving the conflict, David!

**Comment by david-janssen** [comment]
My pleasure, it reminded me to check the documentation further, and there were actually loads of references to the old URL, so I fixed those too.

**Pull request merged**
