### PR TITLE
Replace existing Nix code with a Nix flake

### PR DESCRIPTION
**Pull request by pjones**
Using the New Nix Flake
=======================

For Development
---------------

If you use [direnv](https://direnv.net/) then the included top-level
`.envrc` will load the development environment into your shell/editor
for you.

Otherwise, change into the `nix` directory and run `nix develop` and
you will be dropped into a shell with all of the Haskell tools you
expect.

Using the KMonad NixOS Module
-----------------------------

Create your own `flake.nix` that looks something like this:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/release-22.05";
    kmonad.url = "github:kmonad/kmonad?dir=nix";
  };

  outputs = { self, nixpkgs, kmonad }: {
    nixosConfigurations.my_host_name = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        kmonad.nixosModules.default
        ./path/to/configuration.nix
      ];
    };
  };
}
```

More information can be found here:

  <https://nixos.wiki/wiki/Flakes>

Building KMonad with Various Versions of GHC
--------------------------------------------

    $ cd nix
    $ nix build .#kmonad-ghc8107
    $ nix build .#kmonad-ghc902
    $ nix build .#kmonad-ghc922

Running the NixOS Virtual Machine Tests
---------------------------------------

    $ cd nix
    $ nix flake check

### CODE REVIEW

**Comment by pjones** [comment]
This is a WIP because the NixOS tests are not passing.  For some reason KMonad isn't intercepting the keyboard events in the QEMU test VM.  When I figure out what's going on I'll push another commit and remove the WIP flag.

**Comment by pjones** [comment]
NixOS tests have been fixed.  This is ready to merge.

**Comment by david-janssen** [comment]
Oops, I did a silly thing.

I merged this early in the morning before coffee, trusting the verified checks and such. However, the moment I tried this it came with a bunch of errors. I quickly reverted the pull-request, because I didn't want master to exist publicly exist in a state that, at least for me, was not working. Then I discovered that I can't reopen pull-requests on Github. Please forgive my clumsiness :-).

Would you be so kind as to submit a new pull request? 

I'm going to already list the errors I ran into here right now, but I'll copy-paste them into the new pull-request when you make it. Additionally, I'll make sure to try things before merging them from now on. Hubris.

Cheerio,

D

I'm not even sure if these errors are a problem with the nix-code in this pull-request, or if I am not running the right nix-setup (e.g. `nix` version and `nix-channel` settings) on my own system.

Trying to enable direnv
```
$ direnv allow
direnv: loading ~/prj/kmonad/.envrc
direnv: using flake /home/david/prj/kmonad/nix
error: 'print-dev-env' is not a recognised command
Try '/nix/store/93p5wvnxngf7xi1xq5agrs61amsy0fp4-nix-2.3.16/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/93p5wvnxngf7xi1xq5agrs61amsy0fp4-nix-2.3.16/bin/nix --help' for more information.
```

Trying to nix develop
```
(./nix)$ nix develop
error: flake 'git+file:///home/david/prj/kmonad?dir=nix' does not provide attribute 'devShells.x86_64-linux.devShell.x86_64-linux', 'packages.x86_64-linux.devShell.x86_64-linux', 'legacyPackages.x86_64-linux.devShell.x86_64-linux', 'devShell.x86_64-linux' or 'defaultPackage.x86_64-linux
```

**Comment by david-janssen** [comment]
Figured out that I can actually create the pull-request myself, so, now open in: #551

**Pull request merged**
