### PR TITLE
Add build instructions for Windows (using scoop)

### PR DESCRIPTION
**Pull request by MaxGyver83**
Add build instructions for Windows (using scoop)

### CODE REVIEW

**Comment by david-janssen** [comment]
Thank you very much

**Comment by slotThe** [comment]
@david-janssen I assume you didn't actually mean to close this? :)

**Comment by david-janssen** [comment]
@david-janssen I assume you didn't actually mean to close this? :)

D'oh! Well caught and thanks.

**Comment by MaxGyver83** [comment]
I just noticed that the KMonad repo has been moved to the KMonad organization. Thus my PR is already outdated as it contains a `git clone https://github.com/david-janssen/kmonad.git`. This is the updated PR: https://github.com/kmonad/kmonad/pull/240

**Comment by david-janssen** [comment]
Hah, I pull it and immediately break it. Well done me!

**Pull request merged**
