### PR TITLE
Add Arabic chars

### PR DESCRIPTION
**Pull request by mdSlash**

### CODE REVIEW

**Comment by mdSlash** [comment]
#811

**Comment by slotThe** [comment]
@mdSlash as you can see from the CI, it seems like GHC does not like some Unicode endpoints and you'll have to use the appropriate escape sequence instead

**Comment by mdSlash** [comment]
@slotThe I tried to fix the Unicode problem. I hope it's working now!

Will it be possible to use Arabic chars inside layers without showing a `Parse error` message, without needing to use compose-key sequences in the `tap-macro` functions?

**Comment by slotThe** [comment]
> Will it be possible to use Arabic chars inside layers without showing a `Parse error` message, without needing to use compose-key sequences in the `tap-macro` functions?

You tell me, it's your PR! :) I would think so, but this should obviously be tested before this is merged

**Comment by mdSlash** [comment]
@slotThe I'm stuck here and have no idea what to do next. You can close this pull request if you're not making any edits to it. Thanks.

**Comment by mdSlash** [comment]
> Try `\x` instead of `\u`

I will try it. Thanks for your help.

**Pull request closed without merging**
